export const FEEDS: string[] = [
  // Existing feeds
  "https://rss.cnn.com/rss/edition.rss",
  "https://feeds.foxnews.com/foxnews/latest",
  "https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml",
  "https://feeds.bbci.co.uk/news/rss.xml",
  "https://www.aljazeera.com/xml/rss/all.xml",
  "https://www.reuters.com/world/us/rss",
  "https://www.reuters.com/world/rss",
  "https://www.rt.com/rss/",
  "https://www.theverge.com/rss/index.xml",
  "https://www.cnbc.com/id/100003114/device/rss/rss.html",
  "https://www.rollingstone.com/music/music-news/feed/",
  "https://www.tmz.com/rss.xml",
  "https://nypost.com/entertainment/feed/",

  // Additions from your list
  "https://www.usatoday.com/rss/news/",
  "https://www.newsweek.com/rss",
  "https://news.google.com/rss",
  "https://www.apnews.com/apf-topnews?format=xml",
  "https://news.yahoo.com/rss",
  "https://www.dailymail.co.uk/articles.rss",
  "https://substack.com/feed", // generic feed (varies per writer)
  "https://www.nbcnews.com/id/3032091/device/rss/rss.xml",
  "https://www.theguardian.com/world/rss",
  "https://feeds.a.dj.com/rss/RSSWorldNews.xml", // WSJ
  "https://feeds.washingtonpost.com/rss/national",
  "https://www.cbsnews.com/latest/rss/main",
  "https://www.forbes.com/business/feed/",
  "https://abcnews.go.com/abcnews/topstories", // RSS-ish endpoint
  "https://www.businessinsider.com/rss",
  "https://www.drudgereportfeed.com/rss.xml",
  "https://www.buzzfeed.com/world.xml",
  "https://www.politico.com/rss/politics08.xml",
  "https://www.huffpost.com/section/front-page/feed",
  "https://www.breitbart.com/feed/",
  "https://thehill.com/feed/",
  "https://www.newsbreak.com/rss",
  "https://www.axios.com/feed",
  "https://variety.com/feed/",
  "https://www.the-sun.com/feed/",
  "https://timesofindia.indiatimes.com/rss.cms",
  "https://www.sfgate.com/rss/",
  "https://www.newsmax.com/rss/",
  "https://patch.com/rss",
  "https://www.thegatewaypundit.com/feed/",
  "https://www.usnews.com/rss/news",
  "https://www.latimes.com/world-nation/rss2.0.xml",
  "https://www.bloomberg.com/feed/podcast/etf-report.xml", // limited RSS availability
  "https://www.sciencealert.com/feed",
  "https://www.theatlantic.com/feed/all/",
  "https://www.zerohedge.com/fullrss2.xml",
  "https://www.ksl.com/rss/news",
  "https://www.msnbc.com/feeds/latest",
  "https://www.today.com/feeds/latest",
  "https://www.thedailybeast.com/feeds/rss"
];
