export const FEEDS: string[] = [
  "https://rss.cnn.com/rss/edition.rss",
  "https://feeds.foxnews.com/foxnews/latest",
  "https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml",
  "https://feeds.bbci.co.uk/news/rss.xml",
  "https://www.aljazeera.com/xml/rss/all.xml",
  "https://www.reuters.com/world/us/rss",
  "https://www.reuters.com/world/rss",
  "https://www.rt.com/rss/",
  "https://www.theverge.com/rss/index.xml",
  "https://www.cnbc.com/id/100003114/device/rss/rss.html",
  "https://www.rollingstone.com/music/music-news/feed/",
  "https://www.tmz.com/rss.xml",
  "https://nypost.com/entertainment/feed/",
];
